version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    expose:
      - 27017
    volumes: /data/db:/data/db
  app:
    image: satvikr/hw-api:latest
    container_name: app
    ports:
      - 8080:8000
    env_file:
      - ./.env
