version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    expose:
      - 27017
    volumes: ["/data/db:/data/db"]
  app:
    image: satvikr/hw-api:latest
    container_name: app
    depends_on:
      - mongo
    ports:
      - 8080:8000
    env_file:
      - ./.env
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    volumes: ["/data/redis:/data"]
    command: ["redis-server", "--appendonly", "yes"]
