name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hw-api:latest
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DB_URI: ${{ secrets.DB_URI }}
          envkey_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          envkey_REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          envkey_REDIS_URL: ${{ secrets.REDIS_URL }}
          envkey_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_COMPOSE_PROJECT_NAME: hw-api
          file_name: .env
      - name: Copy Build files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          source: ".env,docker-compose.yml"
          target: "~"
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            sudo docker-compose down
            sudo docker rmi satvikr/hw-api:latest
            sudo docker-compose up -d
